name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DVC
        run: pip install dvc[all]

      - name: Configure DVC Remote
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DVC_USER }}
          dvc remote modify origin --local password ${{ secrets.DVC_PASS }}

      - name: Pull Data & Models
        run: dvc pull

      - name: Run Unit Tests
        run: pytest tests/

      - name: Train Model
        run: dvc repro

      - name: Push Artifacts
        run: |
          dvc push
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add dvc.lock metrics.json
          git commit -m "Updated model & metrics [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Build Docker Image
        run: docker build -t my_ml_pipeline .

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my_ml_pipeline mydockerhubuser/my_ml_pipeline:latest
          docker push mydockerhubuser/my_ml_pipeline:latest
